### ISSUE TITLE
When trying the full example, "Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper" is thrown 

### ISSUE THREAD

**Issue by ZSvedic** [architsharma97/dpo-rlaif#8]
Tried to reproduce [A Complete Example](https://github.com/architsharma97/dpo-rlaif/blob/main/README.md#a-complete-example) on lambdalabs.com gpu_8x_a100_80gb_sxm4, but I am getting the following exception:
```
-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/train.py", line 44, in worker_main
    trainer = TrainerClass(policy, config, config.seed, config.local_run_dir, reference_model=reference_model, rank=rank, world_size=world_size)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/trainers.py", line 505, in __init__
    super().__init__(policy, config, seed, run_dir, reference_model, rank, world_size)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/trainers.py", line 163, in __init__
    self.tokenizer = transformers.AutoTokenizer.from_pretrained(tokenizer_name_or_path)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 768, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
    return cls._from_pretrained(
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 124, in __init__
    super().__init__(
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 40 column 3
```

Anybody has an idea why is that happening?

My library versions:
```
accelerate==0.27.2
aiohttp==3.9.3
aiosignal==1.3.1
alpaca-eval==0.3.0
annotated-types==0.6.0
anthropic==0.14.0
antlr4-python3-runtime==4.9.3
anyio==4.3.0
appdirs==1.4.4
asttokens==2.4.1
async-timeout==4.0.3
attrs==23.2.0
beautifulsoup4==4.12.2
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
cmake==3.28.3
comm==0.2.1
datasets==2.16.1
debugpy==1.8.1
decorator==5.1.1
dill==0.3.7
distro==1.9.0
docker-pycreds==0.4.0
exceptiongroup==1.2.0
executing==2.0.1
filelock==3.13.1
fire==0.5.0
frozenlist==1.4.1
fsspec==2023.10.0
gitdb==4.0.11
GitPython==3.1.42
h11==0.14.0
httpcore==1.0.3
httpx==0.26.0
huggingface-hub==0.20.3
hydra-core==1.3.2
idna==3.6
ipykernel==6.23.1
ipython==8.21.0
jedi==0.19.1
Jinja2==3.1.3
jupyter_client==8.6.0
jupyter_core==5.7.1
lit==17.0.6
MarkupSafe==2.1.5
matplotlib-inline==0.1.6
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.15
nest-asyncio==1.6.0
networkx==3.2.1
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
openai==0.28.1
packaging==23.2
pandas==2.2.0
parso==0.8.3
pathtools==0.1.2
peft==0.8.2
pexpect==4.9.0
pip==22.0.2
platformdirs==4.2.0
prompt-toolkit==3.0.43
protobuf==4.25.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==15.0.0
pyarrow-hotfix==0.6
pydantic==2.6.1
pydantic_core==2.16.2
Pygments==2.17.2
python-dateutil==2.8.2
python-dotenv==1.0.1
pytz==2024.1
PyYAML==6.0.1
pyzmq==25.1.2
regex==2023.12.25
requests==2.31.0
safetensors==0.4.2
sentry-sdk==1.40.5
setproctitle==1.3.3
setuptools==59.6.0
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.5
stack-data==0.6.3
sympy==1.12
tensor-parallel==1.2.4
termcolor==2.4.0
tiktoken==0.6.0
tokenizers==0.15.1
torch==2.0.1
tornado==6.4
tqdm==4.65.0
traitlets==5.14.1
transformers==4.35.2
triton==2.0.0
typing_extensions==4.9.0
tzdata==2024.1
urllib3==2.2.1
wandb==0.15.3
wcwidth==0.2.13
wheel==0.42.0
xxhash==3.4.1
yarl==1.9.4
```

And the full console output:
```
(.venv-tm20240220) ubuntu@129-213-88-46:~/va-us-east-1/dpo-rlaif$ python -u train.py loss=sft model=mistral7b datasets=[sharegpt] exp_name=sharegpt_mistral7b eval_batch_size=16 sample_during_eval=false debug=false lr=1e-6 trainer=FSDPTrainer activation_checkpointing=True data_fraction=0.1 save_every=epoch_3 n_epochs=9
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/.cache/huggingface/token
Login successful
seed: 0
exp_name: sharegpt_mistral7b
batch_size: 8
eval_batch_size: 16
debug: false
fsdp_port: 12355
datasets:
- sharegpt
wandb:
  enabled: true
  entity: null
  project: dpo-rlaif
local_dirs:
- /home/ubuntu/.cache
sample_during_eval: false
n_eval_model_samples: 16
do_first_eval: true
local_run_dir: /home/ubuntu/zel-ca-us-west-1/CACHE/sharegpt_mistral7b_2024-11-20_15-57-11_151741
lr: 1.0e-06
gradient_accumulation_steps: 1
max_grad_norm: 10.0
max_length: 512
max_prompt_length: 256
n_epochs: 9
n_examples: null
n_eval_examples: 64
trainer: FSDPTrainer
optimizer: RMSprop
warmup_steps: 0
activation_checkpointing: true
eval_every: 5000
minimum_log_interval_secs: 1.0
save_every: epoch_3
trigger_alpaca_eval: false
eval_gpu: 6
prefs_path: null
num_turns: 1
data_fraction: 0.1
model:
  name_or_path: mistralai/Mistral-7B-v0.1
  tokenizer_name_or_path: null
  archive: null
  block_name: MistralDecoderLayer
  policy_dtype: float32
  fsdp_policy_mp: null
  reference_dtype: float16
loss:
  name: sft

================================================================================
Writing to 129-213-88-46:/home/ubuntu/zel-ca-us-west-1/CACHE/sharegpt_mistral7b_2024-11-20_15-57-11_151741
================================================================================
building policy
Loading checkpoint shards: 100%|██████████████████████████████████████| 2/2 [00:01<00:00,  1.02it/s]
starting 8 processes for FSDP training
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/zel-ca-us-west-1/CACHE/huggingface/token
Login successful
0 initializing distributed
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/zel-ca-us-west-1/CACHE/huggingface/token
Login successful
1 initializing distributed
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/zel-ca-us-west-1/CACHE/huggingface/token
Login successful
2 initializing distributed
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/zel-ca-us-west-1/CACHE/huggingface/token
Login successful
3 initializing distributed
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/zel-ca-us-west-1/CACHE/huggingface/token
Login successful
4 initializing distributed
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/zel-ca-us-west-1/CACHE/huggingface/token
Login successful
5 initializing distributed
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/zel-ca-us-west-1/CACHE/huggingface/token
Login successful
6 initializing distributed
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /home/ubuntu/zel-ca-us-west-1/CACHE/huggingface/token
Login successful
7 initializing distributed
Creating trainer on process 4 with world size 8
Creating trainer on process 7 with world size 8
Creating trainer on process 6 with world size 8
Creating trainer on process 2 with world size 8
Creating trainer on process 5 with world size 8
Creating trainer on process 1 with world size 8
Creating trainer on process 3 with world size 8
Error executing job with overrides: ['loss=sft', 'model=mistral7b', 'datasets=[sharegpt]', 'exp_name=sharegpt_mistral7b', 'eval_batch_size=16', 'sample_during_eval=false', 'debug=false', 'lr=1e-6', 'trainer=FSDPTrainer', 'activation_checkpointing=True', 'data_fraction=0.1', 'save_every=epoch_3', 'n_epochs=9']
Traceback (most recent call last):
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/train.py", line 105, in main
    mp.spawn(worker_main, nprocs=world_size, args=(world_size, config, policy, reference_model), join=True)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/train.py", line 44, in worker_main
    trainer = TrainerClass(policy, config, config.seed, config.local_run_dir, reference_model=reference_model, rank=rank, world_size=world_size)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/trainers.py", line 505, in __init__
    super().__init__(policy, config, seed, run_dir, reference_model, rank, world_size)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/trainers.py", line 163, in __init__
    self.tokenizer = transformers.AutoTokenizer.from_pretrained(tokenizer_name_or_path)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 768, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
    return cls._from_pretrained(
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 124, in __init__
    super().__init__(
  File "/home/ubuntu/va-us-east-1/dpo-rlaif/.venv-tm20240220/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 40 column 3


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by ZSvedic** [comment]
To answer my own question, the library versions were fine. 

The problematic exception is thrown when there is not enough VRAM, I tried it on 1 A100. When I used the original script on 4 x A100 80GB, the exception disappeared.
